# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 07:29
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Database')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='databases',
            field=models.ManyToManyField(to='users.Database'),
        ),
    ]
